### PR TITLE
feat: introduce retry mechanism for session

### PR DESCRIPTION
**Pull request by sachinshaji**

### CODE REVIEW

**Comment by sachinshaji** [comment]
Closing this PR as the script needs more work to introduce session in sw360 api. Will work on this and create new PR.

**Comment by gernot-h** [comment]
@sachinshaji, I think it would be helpful if we could either keep this open, marked as draft or if you would create an issue so that others know that you're working on it, what do you think? Or do you expect to get this ready within few days?

**Comment by gernot-h** [comment]
And, before investing more effort here, did you discuss your scenario and plans with @tngraf? If not, I would in any case suggest to first create an issue to describe your use case and planned implementation, so that we can agree on it before you invest more effort on the implementation.

**Comment by sachinshaji** [comment]
@gernot-h Thanks for the insights. I should have created an issue before start working. Apologies for missing that. I already have completed working on this and give a new PR today. Thanks in advance.

**Pull request closed without merging**
