### PR TITLE
Introduce session and re-try for all api responses

### PR DESCRIPTION
**Pull request by sachinshaji**
•	Introduce session as a parameter to the main sw360.SW360 class, so that  user can define their own session (Eg: client = sw360.SW360(https://stage1.sw360.siemens.com/, token, oauth2=OAUTH2, session=session_default))
•	Session will be used by all the api requests.

### CODE REVIEW

**Comment by gernot-h** [comment]
@sachinshaji, could you please describe your use cases / reasons which lead to these changes? I guess this would need also some user documentation update and mentioning in the ChangeLog. So far, I didn't look into the actual implementation details due to lack of time.

**Comment by sachinshaji** [comment]
@gernot-h Thanks for the comments.
Motivation for the changes --> When using sw360 api in our python code we are hitting with 500 series error very frequently and this causes our pipeline to fail. Session is only added to GET api calls and it doesn't has any re-try mechanism, hence modified the code to introduce session(with retry) as a parameter in this sw360 api. Session is also added to all api requests.

**Comment by tngraf** [comment]
Please run `flake8` locally and fix all issues.

**Comment by sachinshaji** [comment]
Sure Thomas, will do it.

**Comment by tngraf** [comment]
Unit test do not run on my machines!  
`tests/test_sw360_base.py::Sw360Test::test_login_failed_invalid_url` seems to run forever...

**Pull request merged**
