### PR TITLE
Update(api): Update get all release api

### PR DESCRIPTION
**Pull request by its-sushant**
Fix: https://github.com/sw360/sw360python/issues/37
CC: @deveaud-m

### CODE REVIEW

**Comment by gernot-h** [comment]
Dear @its-sushant, thanks for your contibution! Would you mind adding an entry about the feature you added also to ChangeLog.md? And if you're at it, you might also want to consider adding the good explanation you provided in #37 also to the commit comment?

**Comment by gernot-h** [comment]
By the way, do you know when this feature was added to SW360? I quickly checked in https://github.com/eclipse-sw360/sw360/blob/main/CHANGELOG.md, but couldn't find it at a first glance - might be helpful to also add this bit to the ChangeLog so users know if it's available or not.

**Comment by gernot-h** [comment]
> By the way, do you know when this feature was added to SW360? I quickly checked in https://github.com/eclipse-sw360/sw360/blob/main/CHANGELOG.md, but couldn't find it at a first glance - might be helpful to also add this bit to the ChangeLog so users know if it's available or not.

Ok, found https://github.com/eclipse-sw360/sw360/pull/2657/, so I guess it's expected to be part of SW360 19.1, right?

**Comment by tngraf** [comment]
Hi @its-sushant,
you also may want to add a unit test.

**Comment by its-sushant** [comment]
> Hi @its-sushant, you also may want to add a unit test.

Thank you @tngraf. I have added the unit test for the parameter.

**Comment by its-sushant** [comment]
> Dear @its-sushant, thanks for your contibution! Would you mind adding an entry about the feature you added also to ChangeLog.md? And if you're at it, you might also want to consider adding the good explanation you provided in #37 to the commit comment?

Thank You @gernot-h for the review. I have updated the changelog for this PR and also updated the commit message.

**Comment by its-sushant** [comment]
> > By the way, do you know when this feature was added to SW360? I quickly checked in https://github.com/eclipse-sw360/sw360/blob/main/CHANGELOG.md, but couldn't find it at a first glance - might be helpful to also add this bit to the ChangeLog so users know if it's available or not.
> 
> Ok, found [eclipse-sw360/sw360#2657](https://github.com/eclipse-sw360/sw360/pull/2657), so I guess it's expected to be part of SW360 19.1, right?

Yes, I guess.

**Comment by gernot-h** [comment]
Thanks, @its-sushant, for addressing my comments! Change looks good to me now, I also triggered the unit tests, so @tngraf can merge if he agrees…

**Comment by tngraf** [comment]
Thanks, @its-sushant, @gernot-h, @deveaud-m

**Pull request merged**
